$(function(){
    $("#navbar").load("sections/navbar.html"); 
    $("#home").load("sections/home.html"); 
    $("#education").load("sections/education.html"); 
    $("#experience").load("sections/experience.html"); 
    $("#skills").load("sections/skills.html"); 
    $("#portfolio").load("sections/portfolio.html"); 
    $("#about").load("sections/about.html"); 
    $("#footer").load("sections/footer.html"); 
});